//! Structural checks on the committed quality corpus (review R11).
//!
//! The corpus is `data/eval/quality.tsv`, generated by
//! `scripts/generate_eval_corpus.py` from the pinned dictionary. These checks are
//! the automatic dev/test-separation gate the iteration requires: they run in the
//! normal test suite, so a regenerated or hand-edited corpus cannot silently leak
//! a test input into the development half.
//!
//! Scope is limited to corpus structure. Accuracy numbers live in
//! `docs/QUALITY_BASELINE.md`, produced by the `quality_report` example.

use myswy_core::{Dictionary, Key, Modifiers, Profile, Session};
use std::collections::{BTreeSet, HashMap};
use std::sync::Arc;

const CORPUS: &str = include_str!("../../../data/eval/quality.tsv");

const CATEGORIES: [&str; 9] = [
    "whole_word",
    "single_char",
    "long_sentence",
    "homophone",
    "fuzzy",
    "typo",
    "initials",
    "prefix",
    "learning",
];

struct Row {
    category: String,
    split: String,
    flags: u32,
    input: String,
    expected: String,
    train: String,
    bucket: String,
}

fn load() -> Vec<Row> {
    let mut rows = Vec::new();
    for (index, line) in CORPUS.lines().enumerate() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(
            fields.len(),
            8,
            "line {}: {} fields",
            index + 1,
            fields.len()
        );
        rows.push(Row {
            category: fields[0].to_owned(),
            split: fields[1].to_owned(),
            flags: fields[2].parse().expect("flags"),
            input: fields[3].to_owned(),
            expected: fields[4].to_owned(),
            train: fields[5].to_owned(),
            bucket: fields[6].to_owned(),
        });
    }
    assert!(!rows.is_empty(), "corpus is empty");
    rows
}

/// The separation gate the iteration requires: a typed spelling must never appear
/// in both halves. The same spelling may legitimately recur across categories in
/// one half (a learning row and a whole-word row can share a key), so only the
/// cross-split intersection is a defect.
#[test]
fn dev_and_test_splits_share_no_input_string() {
    let rows = load();
    let mut dev = BTreeSet::new();
    let mut test = BTreeSet::new();
    for row in &rows {
        match row.split.as_str() {
            "dev" => {
                dev.insert(row.input.as_str());
            }
            "test" => {
                test.insert(row.input.as_str());
            }
            other => panic!("unknown split {other}"),
        }
    }
    let overlap: Vec<_> = dev.intersection(&test).collect();
    assert!(overlap.is_empty(), "dev/test input overlap: {overlap:?}");
    assert!(
        dev.len() >= 100 && test.len() >= 100,
        "splits are too small"
    );
}

#[test]
fn every_category_has_both_splits_and_difficulty_buckets() {
    let rows = load();
    let mut per_category: HashMap<&str, HashMap<&str, usize>> = HashMap::new();
    for row in &rows {
        *per_category
            .entry(row.category.as_str())
            .or_default()
            .entry(row.split.as_str())
            .or_default() += 1;
    }
    for category in CATEGORIES {
        let counts = per_category
            .get(category)
            .unwrap_or_else(|| panic!("category {category} is missing"));
        for split in ["dev", "test"] {
            assert!(
                counts.get(split).copied().unwrap_or(0) >= 10,
                "category {category} has too few {split} rows: {counts:?}"
            );
        }
    }
    assert_eq!(per_category.len(), CATEGORIES.len(), "unexpected category");
    let buckets: BTreeSet<&str> = rows.iter().map(|row| row.bucket.as_str()).collect();
    assert!(
        buckets.len() >= 20,
        "difficulty buckets collapsed: {buckets:?}"
    );
}

#[test]
fn declared_flags_stay_within_the_supported_matching_mask() {
    let rows = load();
    let mut seen = BTreeSet::new();
    for row in &rows {
        assert_eq!(
            row.flags & !myswy_core::fuzzy::OPTIONS_MASK,
            0,
            "{}: unsupported flag bits {}",
            row.input,
            row.flags
        );
        seen.insert(row.flags);
    }
    // The corpus must actually exercise matching: plain rows plus fuzzy and typo rows.
    assert!(seen.contains(&0), "no flags-off rows");
    let flagged = seen.iter().filter(|&&flags| flags != 0).count();
    assert!(
        flagged >= 5,
        "too few distinct flag combinations: {flagged}"
    );
}

/// Every row must be playable: the input is accepted, the preedit is intact, and
/// the composition stays inside the ambiguity budget. Whether the expected text
/// is actually *offered* is deliberately NOT asserted here — that is the engine
/// property being measured, and the report counts rows where it is missing as
/// `unreachable` rather than hiding the failure.
#[test]
fn every_row_is_playable() {
    let dictionary =
        Arc::new(Dictionary::from_binary(include_bytes!("../../../data/daily.mswydict")).unwrap());
    let rows = load();
    for row in &rows {
        let mut session = Session::new(Arc::clone(&dictionary));
        assert!(session.configure(9, true, false));
        assert!(
            session.configure_matching(row.flags),
            "{}: flags rejected",
            row.input
        );
        let mut profile = Profile::default();
        for step in row.train.split(';').filter(|step| !step.is_empty()) {
            let body = step.strip_prefix("record:").unwrap_or_else(|| {
                panic!(
                    "{}: only record: steps are supported, got {step:?}",
                    row.input
                )
            });
            let (spelling, text) = body.split_once("=>").expect("train step");
            // Each train step is a selection the host already confirmed, recorded
            // through the same API the platform adapter uses for a saved profile.
            assert!(
                profile.record(spelling, text),
                "{}: rejected train step {step}",
                row.input
            );
        }
        assert!(session.set_profile(Arc::new(profile)));
        let mut limited = false;
        for character in row.input.chars() {
            let result = session.process(Key::Character(character), Modifiers::default());
            limited |= result.limited;
        }
        assert!(!limited, "{}: input hit the ambiguity budget", row.input);
        assert_eq!(session.preedit(), row.input, "preedit mismatch");
        assert!(!row.expected.is_empty(), "{}: empty expectation", row.input);
    }
}
