// SPDX-License-Identifier: GPL-3.0-or-later
//! Structural checks on the committed quality corpus (review R11).
//!
//! The corpus is `data/eval/quality.tsv`, generated by
//! `scripts/generate_eval_corpus.py` from the pinned dictionary. These checks are
//! the automatic dev/test-separation gate the iteration requires: they run in the
//! normal test suite, so a regenerated or hand-edited corpus cannot silently leak
//! a test input into the development half.
//!
//! Scope is limited to corpus structure. Accuracy numbers live in
//! `docs/QUALITY_BASELINE.md`, produced by the `quality_report` example.

use chengyin_core::{Dictionary, Key, Modifiers, Profile, Session};
use std::collections::{BTreeSet, HashMap};
use std::sync::Arc;

const CORPUS: &str = include_str!("../../../data/eval/quality.tsv");

const CATEGORIES: [&str; 11] = [
    "whole_word",
    "single_char",
    "long_sentence",
    "homophone",
    "fuzzy",
    "typo",
    "initials",
    "prefix",
    "learning",
    "alias",
    "learn",
];

struct Row {
    category: String,
    split: String,
    flags: u32,
    input: String,
    expected: String,
    train: String,
    bucket: String,
}

fn load() -> Vec<Row> {
    let mut rows = Vec::new();
    for (index, line) in CORPUS.lines().enumerate() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(
            fields.len(),
            8,
            "line {}: {} fields",
            index + 1,
            fields.len()
        );
        rows.push(Row {
            category: fields[0].to_owned(),
            split: fields[1].to_owned(),
            flags: fields[2].parse().expect("flags"),
            input: fields[3].to_owned(),
            expected: fields[4].to_owned(),
            train: fields[5].to_owned(),
            bucket: fields[6].to_owned(),
        });
    }
    assert!(!rows.is_empty(), "corpus is empty");
    rows
}

/// The separation gate the iteration requires: a typed spelling must never appear
/// in both halves. The same spelling may legitimately recur across categories in
/// one half (a learning row and a whole-word row can share a key), so only the
/// cross-split intersection is a defect.
#[test]
fn dev_and_test_splits_share_no_input_string() {
    let rows = load();
    let mut dev = BTreeSet::new();
    let mut test = BTreeSet::new();
    for row in &rows {
        match row.split.as_str() {
            "dev" => {
                dev.insert(row.input.as_str());
            }
            "test" => {
                test.insert(row.input.as_str());
            }
            other => panic!("unknown split {other}"),
        }
    }
    let overlap: Vec<_> = dev.intersection(&test).collect();
    assert!(overlap.is_empty(), "dev/test input overlap: {overlap:?}");
    assert!(
        dev.len() >= 100 && test.len() >= 100,
        "splits are too small"
    );
}

#[test]
fn every_category_has_both_splits_and_difficulty_buckets() {
    let rows = load();
    let mut per_category: HashMap<&str, HashMap<&str, usize>> = HashMap::new();
    for row in &rows {
        *per_category
            .entry(row.category.as_str())
            .or_default()
            .entry(row.split.as_str())
            .or_default() += 1;
    }
    for category in CATEGORIES {
        let counts = per_category
            .get(category)
            .unwrap_or_else(|| panic!("category {category} is missing"));
        for split in ["dev", "test"] {
            assert!(
                counts.get(split).copied().unwrap_or(0) >= 10,
                "category {category} has too few {split} rows: {counts:?}"
            );
        }
    }
    assert_eq!(per_category.len(), CATEGORIES.len(), "unexpected category");
    let buckets: BTreeSet<&str> = rows.iter().map(|row| row.bucket.as_str()).collect();
    assert!(
        buckets.len() >= 20,
        "difficulty buckets collapsed: {buckets:?}"
    );
}

#[test]
fn declared_flags_stay_within_the_supported_matching_mask() {
    let rows = load();
    let mut seen = BTreeSet::new();
    for row in &rows {
        assert_eq!(
            row.flags & !chengyin_core::fuzzy::OPTIONS_MASK,
            0,
            "{}: unsupported flag bits {}",
            row.input,
            row.flags
        );
        seen.insert(row.flags);
    }
    // The corpus must actually exercise matching: plain rows plus fuzzy and typo rows.
    assert!(seen.contains(&0), "no flags-off rows");
    let flagged = seen.iter().filter(|&&flags| flags != 0).count();
    assert!(
        flagged >= 5,
        "too few distinct flag combinations: {flagged}"
    );
}

/// Every row must be playable: the input is accepted, the preedit is intact, and
/// the composition stays inside the ambiguity budget. Whether the expected text
/// is actually *offered* is deliberately NOT asserted here — that is the engine
/// property being measured, and the report counts rows where it is missing as
/// `unreachable` rather than hiding the failure.
#[test]
fn every_row_is_playable() {
    let dictionary =
        Arc::new(Dictionary::from_binary(include_bytes!("../../../data/daily.mswydict")).unwrap());
    let rows = load();
    for row in &rows {
        let mut session = Session::new(Arc::clone(&dictionary));
        assert!(session.configure(9, true, false));
        assert!(
            session.configure_matching(row.flags),
            "{}: flags rejected",
            row.input
        );
        let mut profile = Profile::default();
        for step in row.train.split(';').filter(|step| !step.is_empty()) {
            // Only the profile-only steps are replayed here; the structural gate
            // checks that a row is playable, and a `ctx:` step needs the live
            // session, which `quality_report` already exercises end to end.
            if step.starts_with("ctx:") || step.starts_with("idle:") {
                continue;
            }
            let body = step
                .strip_prefix("record:")
                .unwrap_or_else(|| panic!("{}: unknown train step kind, got {step:?}", row.input));
            let (spelling, text) = body.split_once("=>").expect("train step");
            // Each train step is a selection the host already confirmed, recorded
            // through the same API the platform adapter uses for a saved profile.
            assert!(
                profile.record(spelling, text),
                "{}: rejected train step {step}",
                row.input
            );
        }
        assert!(session.set_profile(Arc::new(profile)));
        let mut limited = false;
        for character in row.input.chars() {
            let result = session.process(Key::Character(character), Modifiers::default());
            limited |= result.limited;
        }
        assert!(!limited, "{}: input hit the ambiguity budget", row.input);
        assert_eq!(session.preedit(), row.input, "preedit mismatch");
        assert!(!row.expected.is_empty(), "{}: empty expectation", row.input);
    }
}

/// The `learn` category's context scenario is a proof, not a sample, and this test
/// is what keeps it one.
///
/// Each context pair is two rows for one key with byte-identical training whose
/// trailing `ctx:` step differs and whose expectations differ. An engine that does
/// not condition on the preceding word answers both from the same state, so it
/// returns one word for the two and can match at most one — which is exactly the
/// 50% Top-1 the baseline reports. If a regeneration, a hand edit or a re-split
/// ever separated a pair's halves, or made the trained halves differ, the rows would
/// still look plausible while the property they exist to demonstrate was gone.
#[test]
fn learn_context_pairs_are_byte_identical_but_for_the_trailing_context() {
    let rows = load();
    let mut pairs: HashMap<(String, String), Vec<&Row>> = HashMap::new();
    for row in rows.iter().filter(|row| row.bucket == "ln2;context") {
        // The training half is everything before the trailing context step, which
        // is the pair's only intended difference.
        let steps: Vec<&str> = row.train.split(';').collect();
        let (trailing, trained) = steps.split_last().expect("ln2 row has steps");
        assert!(
            trailing.starts_with("ctx:"),
            "{}: the trailing step must be the context, got {trailing:?}",
            row.input
        );
        pairs
            .entry((row.split.clone(), trained.join(";")))
            .or_default()
            .push(row);
    }
    assert!(!pairs.is_empty(), "no ln2;context pairs found");
    for ((split, trained), mut halves) in pairs {
        assert_eq!(
            halves.len(),
            2,
            "{split}/{trained}: a context pair lost a half ({:?})",
            halves.iter().map(|row| &row.expected).collect::<Vec<_>>()
        );
        halves.sort_by(|a, b| a.expected.cmp(&b.expected));
        assert_ne!(
            halves[0].expected, halves[1].expected,
            "{split}/{trained}: both halves expect the same word, so the pair proves nothing"
        );
        assert_ne!(
            halves[0].train, halves[1].train,
            "{split}/{trained}: the two halves must differ in their trailing context"
        );
    }
}
