; NSIS 3.11+, native x64. Payload paths/macros are generated by the packager.
Target amd64-unicode
Unicode true
ManifestSupportedOS all
RequestExecutionLevel admin
SetCompressor /SOLID lzma
CRCCheck force
SetDatablockOptimize on
!include MUI2.nsh
!include LogicLib.nsh
!include FileFunc.nsh
!include TextFunc.nsh
!include x64.nsh
!include "${PAYLOAD_INCLUDE}"

!define PRODUCT "澄音输入法"
!define CLASS "Software\Classes\CLSID\{65C32A54-219A-4F0A-B44C-B963D7BA532F}"
!define ARP "Software\Microsoft\Windows\CurrentVersion\Uninstall\ChengyinIME"
; preview24 and earlier shipped under the former project name: their uninstall
; key, install root, marker and payload file names all carried it. The install
; section detects such a layout, adopts it through the $Old* variables and
; removes the obsolete key, so an in-place upgrade never strands or duplicates
; an older preview.
!define LEGACY_ARP "Software\Microsoft\Windows\CurrentVersion\Uninstall\MyswyIME"
!define ROOT "$PROGRAMFILES64\ChengyinIME"
!define LEGACY_ROOT "$PROGRAMFILES64\MyswyIME"
!define NEW_DLL "chengyin_tsf.dll"
!define LEGACY_DLL "myswy_tsf.dll"
!define NEW_MARKER "chengyin-install.txt"
!define LEGACY_MARKER "myswy-install.txt"
!define NEW_SETTINGS "chengyin_settings.exe"
!define LEGACY_SETTINGS "myswy_settings.exe"
!define LEGACY_PROBE "myswy_probe.exe"
; Revisions 1..6 shipped the settings UI as a standalone "testpad" executable.
!define LEGACY_TESTPAD "myswy_testpad.exe"
; Revisions 1..5 shipped a Start menu folder under the former name.
!define LEGACY_MENU "Myswy 全拼"
Name "${PRODUCT} ${VERSION}"
OutFile "${OUTPUT}"
InstallDir "$PROGRAMFILES64\ChengyinIME\${VERSION}"
BrandingText "Chengyin IME · 离线中文输入法"
VIProductVersion "${NUMERIC_VERSION}"
VIAddVersionKey /LANG=2052 "ProductName" "${PRODUCT}"
VIAddVersionKey /LANG=2052 "FileDescription" "澄音输入法安装程序"
VIAddVersionKey /LANG=2052 "FileVersion" "${VERSION}"
VIAddVersionKey /LANG=2052 "LegalCopyright" "Myswy contributors; MIT"
ShowInstDetails show
ShowUninstDetails show
AutoCloseWindow false

!define MUI_ICON "${__FILEDIR__}/chengyin.ico"
!define MUI_UNICON "${__FILEDIR__}/chengyin.ico"
!define MUI_ABORTWARNING
!define MUI_FINISHPAGE_NOREBOOTSUPPORT
!define MUI_WELCOMEPAGE_TEXT "安装澄音输入法。$\r$\n$\r$\n安装包包含全部运行文件，不需要额外下载运行库。$\r$\n$\r$\n已内置常用词库、整句与首拼输入、选词学习和外观设置。当前为开发预览版。"
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "${PAYLOAD_DIR}/LICENSE"
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_TEXT "安装完成。$\r$\n$\r$\n请注销并重新登录，使用 Win+Space 选择澄音输入法（全拼预览）。尚未添加中文时，先在语言设置中添加中文（简体，中国）。$\r$\n$\r$\n开始菜单的澄音输入法文件夹提供设置、使用说明和卸载；输入测试位于设置内。"
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH
!insertmacro MUI_LANGUAGE "SimpChinese"

Var OldDir
Var OldVersion
Var OldRevision
Var OldDisplayName
Var OldPublisher
Var OldMenu
Var OldHadArp
; Names of the detected previous install. A preview24 or earlier build used the
; former project name in every one of them.
Var OldRoot
Var OldDll
Var OldMarker
Var OldSettings
Var OldTestpad
Var OldArpKey
Var Legacy
Var Failure
Var Phase
Var Registered
Var Mutex

!macro RefuseLink DIR LABEL
  System::Call 'kernel32::GetFileAttributesW(w"${DIR}") i.r0'
  ${If} $0 != -1
    IntOp $0 $0 & 0x400
    ${If} $0 != 0
      StrCpy $Failure "安装目录是链接或重解析点，已停止以保留原文件。"
      Goto ${LABEL}
    ${EndIf}
  ${EndIf}
!macroend

!macro Arp KEY DIR VER REV SETTINGS
  WriteRegStr HKLM "${KEY}" "DisplayName" "${PRODUCT}（预览）"
  WriteRegStr HKLM "${KEY}" "DisplayVersion" "${VER}"
  WriteRegStr HKLM "${KEY}" "InstallLocation" "${DIR}"
  WriteRegStr HKLM "${KEY}" "UninstallString" '$\"${DIR}\Uninstall.exe$\"'
  WriteRegStr HKLM "${KEY}" "QuietUninstallString" '$\"${DIR}\Uninstall.exe$\" /S'
  WriteRegStr HKLM "${KEY}" "DisplayIcon" "${DIR}\${SETTINGS}"
  WriteRegStr HKLM "${KEY}" "Publisher" "Chengyin IME contributors"
  WriteRegDWORD HKLM "${KEY}" "InstallRevision" ${REV}
  WriteRegDWORD HKLM "${KEY}" "NoModify" 1
  WriteRegDWORD HKLM "${KEY}" "NoRepair" 1
  WriteRegDWORD HKLM "${KEY}" "EstimatedSize" ${SIZE_KIB}
!macroend

!macro Links DIR MENU APP_SETTINGS
  CreateDirectory "$SMPROGRAMS\${MENU}"
  Delete "$SMPROGRAMS\${MENU}\输入测试.lnk"
  CreateShortcut "$SMPROGRAMS\${MENU}\设置.lnk" "${DIR}\${APP_SETTINGS}"
  CreateShortcut "$SMPROGRAMS\${MENU}\使用说明.lnk" "${DIR}\README.md"
  CreateShortcut "$SMPROGRAMS\${MENU}\卸载.lnk" "${DIR}\Uninstall.exe"
!macroend

!macro RemoveLinks MENU
  Delete "$SMPROGRAMS\${MENU}\输入测试.lnk"
  Delete "$SMPROGRAMS\${MENU}\设置.lnk"
  Delete "$SMPROGRAMS\${MENU}\使用说明.lnk"
  Delete "$SMPROGRAMS\${MENU}\卸载.lnk"
  RMDir "$SMPROGRAMS\${MENU}"
!macroend

!macro RemoveKnown DIR
  ; Never recursively delete a folder containing unknown or user-created files.
  !insertmacro DeletePayload "${DIR}"
  Delete /REBOOTOK "${DIR}\Uninstall.exe"
  Delete /REBOOTOK "${DIR}\${NEW_MARKER}"
  ; A preview24 or earlier directory still holds the former names.
  Delete /REBOOTOK "${DIR}\${LEGACY_MARKER}"
  Delete /REBOOTOK "${DIR}\chengyin_testpad.exe"
  Delete /REBOOTOK "${DIR}\${LEGACY_TESTPAD}"
  ; A preview24 or earlier directory also holds the former binary names; the
  ; generated payload list above only knows this build's names.
  Delete /REBOOTOK "${DIR}\${LEGACY_DLL}"
  Delete /REBOOTOK "${DIR}\${LEGACY_PROBE}"
  Delete /REBOOTOK "${DIR}\${LEGACY_SETTINGS}"
  ; Files used only by the old preview1 ZIP distribution.
  Delete /REBOOTOK "${DIR}\Install.ps1"
  Delete /REBOOTOK "${DIR}\Uninstall.ps1"
  Delete /REBOOTOK "${DIR}\SHA256SUMS.json"
  RMDir /REBOOTOK "${DIR}"
!macroend

!macro Init PREFIX
Function ${PREFIX}.onInit
  SetRegView 64
  SetShellVarContext all
  System::Call 'kernel32::CreateMutexW(p0,i0,w"Global\ChengyinIME.Setup") p.r0 ?e'
  Pop $1
  StrCpy $Mutex $0
  ${If} $0 == 0
  ${OrIf} $1 == 183
    MessageBox MB_OK|MB_ICONSTOP "另一个澄音安装或卸载正在运行。" /SD IDOK
    SetErrorLevel 1618
    Quit
  ${EndIf}
  ${IfNot} ${IsNativeAMD64}
    MessageBox MB_OK|MB_ICONSTOP "本版本需要 Intel/AMD x64 Windows。" /SD IDOK
    SetErrorLevel 1633
    Quit
  ${EndIf}
  ; RtlGetVersion avoids manifest-dependent version reporting.
  System::Alloc 284
  Pop $0
  System::Call '*$0(i284)'
  System::Call 'ntdll::RtlGetVersion(p r0) i.r1'
  System::Call '*$0(i,i,i,i.r2)'
  System::Free $0
  ${If} $1 != 0
  ${OrIf} $2 < 19041
    MessageBox MB_OK|MB_ICONSTOP "需要 Windows 10 2004 或更新版本。" /SD IDOK
    SetErrorLevel 1633
    Quit
  ${EndIf}
FunctionEnd
!macroend
!insertmacro Init ""
!insertmacro Init "un"

Section "输入法" Install
  StrCpy $Phase 0
  StrCpy $OldDir ""
  StrCpy $OldHadArp 0
  StrCpy $Failure ""
  ; Always use our fixed version directory; /D must not redirect deletion.
  StrCpy $INSTDIR "$PROGRAMFILES64\ChengyinIME\${VERSION}"
  !insertmacro RefuseLink "$PROGRAMFILES64\ChengyinIME" failed
  !insertmacro RefuseLink "$INSTDIR" failed
  InitPluginsDir
  SetOutPath "$PLUGINSDIR\payload"
  ClearErrors
  !insertmacro ExtractPayload
  ${If} ${Errors}
    StrCpy $Failure "安装包解压失败。系统没有被修改。"
    Goto failed
  ${EndIf}
  ClearErrors
  ExecWait '$\"$PLUGINSDIR\payload\chengyin_probe.exe$\" --verify-files $\"$PLUGINSDIR\payload$\" $\"$PLUGINSDIR\payload\SHA256SUMS.txt$\"' $0
  ${If} ${Errors}
  ${OrIf} $0 != 0
    StrCpy $Failure "安装文件校验失败。系统没有被修改。"
    Goto failed
  ${EndIf}
  ExecWait '$\"$PLUGINSDIR\payload\chengyin_probe.exe$\" $\"$PLUGINSDIR\payload\chengyin_tsf.dll$\"' $0
  ${If} ${Errors}
  ${OrIf} $0 != 0
    StrCpy $Failure "输入服务自检失败。系统没有被修改。"
    Goto failed
  ${EndIf}
  ExecWait '$\"$PLUGINSDIR\payload\chengyin_probe.exe$\" --check-registry' $0
  ${If} ${Errors}
  ${OrIf} $0 != 0
    StrCpy $Failure "已有注册信息无法读取或不完整，已保留原文件。"
    Goto failed
  ${EndIf}
  ReadRegStr $Registered HKLM "${CLASS}\InprocServer32" ""
  ; Prefer this build's uninstall entry, then the former-name entry left by a
  ; preview24 or earlier install. Both are adopted before any system change.
  StrCpy $OldArpKey "${ARP}"
  StrCpy $Legacy 0
  ReadRegStr $OldDir HKLM "${ARP}" "InstallLocation"
  ${If} $OldDir == ""
    ReadRegStr $OldDir HKLM "${LEGACY_ARP}" "InstallLocation"
    ${If} $OldDir != ""
      StrCpy $Legacy 1
      StrCpy $OldArpKey "${LEGACY_ARP}"
    ${EndIf}
  ${EndIf}
  ; A former-name install also used the former file, marker and settings names.
  ${If} $Legacy == 1
    StrCpy $OldRoot "${LEGACY_ROOT}"
    StrCpy $OldDll "${LEGACY_DLL}"
    StrCpy $OldMarker "${LEGACY_MARKER}"
    StrCpy $OldSettings "${LEGACY_SETTINGS}"
    StrCpy $OldTestpad "${LEGACY_TESTPAD}"
  ${Else}
    StrCpy $OldRoot "${ROOT}"
    StrCpy $OldDll "${NEW_DLL}"
    StrCpy $OldMarker "${NEW_MARKER}"
    StrCpy $OldSettings "${NEW_SETTINGS}"
    StrCpy $OldTestpad ""
  ${EndIf}
  ${If} $OldDir != ""
    StrCpy $OldHadArp 1
    ReadRegStr $OldDisplayName HKLM "$OldArpKey" "DisplayName"
    ReadRegStr $OldPublisher HKLM "$OldArpKey" "Publisher"
    ReadRegStr $OldVersion HKLM "$OldArpKey" "DisplayVersion"
    ClearErrors
    ReadRegDWORD $OldRevision HKLM "$OldArpKey" "InstallRevision"
    ${If} ${Errors}
      StrCpy $Failure "旧安装版本记录缺失，已保留原文件。"
      Goto failed
    ${EndIf}
  ${ElseIf} $Registered != ""
    ; Explicit migration from the only earlier ZIP release; no generic paths.
    StrCpy $OldRoot "${LEGACY_ROOT}"
    StrCpy $OldDir "${LEGACY_ROOT}\0.1.0-preview1"
    StrCpy $OldVersion "0.1.0-preview1"
    StrCpy $OldRevision 1
    StrCpy $OldDll "${LEGACY_DLL}"
    StrCpy $OldMarker "${LEGACY_MARKER}"
    StrCpy $OldSettings "${LEGACY_SETTINGS}"
    StrCpy $OldTestpad "${LEGACY_TESTPAD}"
  ${EndIf}
  StrCpy $OldMenu "澄音输入法"
  ${If} $OldRevision <= 5
    StrCpy $OldMenu "${LEGACY_MENU}"
  ${EndIf}
  ${If} $OldDir != ""
    ${GetParent} "$OldDir" $0
    ${If} $0 != "$OldRoot"
    ${OrIf} $OldDir != "$OldRoot\$OldVersion"
      StrCpy $Failure "已有注册或安装目录不属于此安装程序，已保留原文件。"
      Goto failed
    ${EndIf}
    ${If} $Registered != ""
    ${AndIf} $Registered != "$OldDir\$OldDll"
      StrCpy $Failure "已有注册或安装目录不属于此安装程序，已保留原文件。"
      Goto failed
    ${EndIf}
    !insertmacro RefuseLink "$OldDir" failed
    ClearErrors
    FileOpen $0 "$OldDir\$OldMarker" r
    FileRead $0 $1
    FileClose $0
    ; The original PowerShell marker has CRLF; newer markers do not.
    ${TrimNewLines} "$1" $1
    ${If} ${Errors}
    ${OrIf} $1 != $OldVersion
      StrCpy $Failure "旧安装标记缺失或不匹配，已保留原文件。"
      Goto failed
    ${EndIf}
    ${If} $OldRevision > ${REVISION}
      StrCpy $Failure "已安装更新版本，拒绝降级。"
      Goto failed
    ${EndIf}
    ${If} $OldDir == $INSTDIR
      ClearErrors
      ExecWait '$\"$PLUGINSDIR\payload\chengyin_probe.exe$\" --verify-files $\"$INSTDIR$\" $\"$PLUGINSDIR\payload\SHA256SUMS.txt$\"' $0
      ${If} ${Errors}
      ${OrIf} $0 != 0
        StrCpy $Failure "同版本文件不同或损坏，请使用更新版本修复。"
        Goto failed
      ${EndIf}
      ExecWait '$\"$SYSDIR\regsvr32.exe$\" /s /n /i:repair $\"$INSTDIR\chengyin_tsf.dll$\"' $0
      ${If} ${Errors}
      ${OrIf} $0 != 0
        StrCpy $Failure "同版本注册修复未完成，已保留文件，可重试。"
        Goto failed
      ${EndIf}
      DetailPrint "相同版本已安装；文件校验和注册修复完成。"
      SetErrorLevel 0
      Goto done
    ${EndIf}
  ${ElseIf} $Registered != ""
    StrCpy $Failure "已有未知注册，未修改系统。"
    Goto failed
  ${EndIf}
  System::Call 'kernel32::GetFileAttributesW(w"$INSTDIR") i.r0'
  ${If} $0 != -1
    StrCpy $Failure "目标目录已存在，请先从已安装的应用完成卸载。"
    Goto failed
  ${EndIf}
  StrCpy $Phase 1
  SetOutPath "$INSTDIR"
  ClearErrors
  CopyFiles /SILENT "$PLUGINSDIR\payload\*.*" "$INSTDIR"
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  FileOpen $0 "$INSTDIR\${NEW_MARKER}" w
  FileWrite $0 "${VERSION}"
  FileClose $0
  ${If} ${Errors}
    StrCpy $Failure "无法写入安装目录。"
    Goto failed
  ${EndIf}
  ExecWait '$\"$PLUGINSDIR\payload\chengyin_probe.exe$\" --verify-files $\"$INSTDIR$\" $\"$PLUGINSDIR\payload\SHA256SUMS.txt$\"' $0
  ${If} ${Errors}
  ${OrIf} $0 != 0
    StrCpy $Failure "复制后的文件校验失败。"
    Goto failed
  ${EndIf}
  ${If} $OldDir != ""
    StrCpy $Phase 2
    ExecWait '$\"$SYSDIR\regsvr32.exe$\" /s /u $\"$OldDir\$OldDll$\"' $0
    ${If} ${Errors}
    ${OrIf} $0 != 0
      StrCpy $Failure "旧服务注销失败，安装已停止并尝试修复旧注册。"
      Goto failed
    ${EndIf}
  ${EndIf}
  StrCpy $Phase 3
  ExecWait '$\"$SYSDIR\regsvr32.exe$\" /s $\"$INSTDIR\${NEW_DLL}$\"' $0
  ${If} ${Errors}
  ${OrIf} $0 != 0
    StrCpy $Failure "新输入服务注册失败。"
    Goto failed
  ${EndIf}
  StrCpy $Phase 4
  ClearErrors
  !insertmacro Arp "${ARP}" "$INSTDIR" "${VERSION}" ${REVISION} "${NEW_SETTINGS}"
  !insertmacro Links "$INSTDIR" "澄音输入法" "${NEW_SETTINGS}"
  ${If} ${Errors}
    StrCpy $Failure "无法写入卸载入口或开始菜单。"
    Goto failed
  ${EndIf}
  ${If} $OldDir != ""
    ${If} $OldMenu != "澄音输入法"
      !insertmacro RemoveLinks "$OldMenu"
    ${EndIf}
    !insertmacro RemoveKnown "$OldDir"
    ; The former-name uninstall entry is now obsolete; the new key owns it.
    ${If} $OldArpKey != "${ARP}"
      DeleteRegKey HKLM "${LEGACY_ARP}"
    ${EndIf}
  ${EndIf}
  SetOutPath "$TEMP"
  DetailPrint "安装成功。请注销并重新登录；默认输入法没有被更改。"
  SetErrorLevel 0
  Goto done

failed:
  ; Compensate only phases begun by this installation. A failed compensation
  ; retains files and an uninstall entry so a later retry can finish cleanup.
  ${If} $Phase >= 3
    ReadRegStr $0 HKLM "${CLASS}\InprocServer32" ""
    ${If} $0 == "$INSTDIR\chengyin_tsf.dll"
      ExecWait '$\"$SYSDIR\regsvr32.exe$\" /s /u $\"$INSTDIR\chengyin_tsf.dll$\"' $1
    ${EndIf}
  ${EndIf}
  ${If} $Phase >= 2
  ${AndIf} $OldDir != ""
    ReadRegStr $0 HKLM "${CLASS}\InprocServer32" ""
    ${If} $0 == ""
      ExecWait '$\"$SYSDIR\regsvr32.exe$\" /s $\"$OldDir\chengyin_tsf.dll$\"' $1
    ${ElseIf} $0 == "$OldDir\chengyin_tsf.dll"
      ExecWait '$\"$SYSDIR\regsvr32.exe$\" /s /n /i:repair $\"$OldDir\chengyin_tsf.dll$\"' $1
    ${EndIf}
  ${EndIf}
  ${If} $Phase >= 4
    ${If} $OldHadArp == 1
      !insertmacro Arp "$OldArpKey" "$OldDir" "$OldVersion" $OldRevision "$OldSettings"
      WriteRegStr HKLM "$OldArpKey" "DisplayName" "$OldDisplayName"
      WriteRegStr HKLM "$OldArpKey" "Publisher" "$OldPublisher"
      ${If} $OldMenu != "澄音输入法"
        !insertmacro RemoveLinks "澄音输入法"
      ${EndIf}
      !insertmacro Links "$OldDir" "$OldMenu" "$OldSettings"
      ${If} $OldRevision <= 6
        WriteRegStr HKLM "$OldArpKey" "DisplayIcon" "$OldDir\$OldTestpad"
        CreateShortcut "$SMPROGRAMS\$OldMenu\设置.lnk" "$OldDir\$OldTestpad" "--settings"
        CreateShortcut "$SMPROGRAMS\$OldMenu\输入测试.lnk" "$OldDir\$OldTestpad"
      ${EndIf}
    ${Else}
      DeleteRegKey HKLM "${ARP}"
      DeleteRegKey HKLM "${LEGACY_ARP}"
      !insertmacro RemoveLinks "澄音输入法"
    ${EndIf}
  ${EndIf}
  ${If} $Phase >= 1
    ReadRegStr $0 HKLM "${CLASS}\InprocServer32" ""
    ${If} $0 == "$INSTDIR\chengyin_tsf.dll"
      !insertmacro Arp "${ARP}" "$INSTDIR" "${VERSION}" ${REVISION} "${NEW_SETTINGS}"
      StrCpy $Failure "$Failure$\r$\n清理未完成；文件和卸载入口已保留，请重试卸载。"
    ${Else}
      SetOutPath "$TEMP"
      !insertmacro RemoveKnown "$INSTDIR"
    ${EndIf}
  ${EndIf}
  DetailPrint "$Failure"
  MessageBox MB_OK|MB_ICONSTOP "$Failure" /SD IDOK
  SetErrorLevel 1
  Abort
done:
SectionEnd

Section "Uninstall"
  ; NSIS runs a temporary copy of the uninstaller. Use the fixed owned version
  ; path, not that copy's EXEDIR or a command-line override.
  StrCpy $INSTDIR "$PROGRAMFILES64\ChengyinIME\${VERSION}"
  !insertmacro RefuseLink "$PROGRAMFILES64\ChengyinIME" un_failed
  !insertmacro RefuseLink "$INSTDIR" un_failed
  ${GetParent} "$INSTDIR" $0
  ${If} $0 != "$PROGRAMFILES64\ChengyinIME"
    StrCpy $Failure "卸载程序不在所属安装目录中。"
    Goto un_failed
  ${EndIf}
  ${IfNot} ${FileExists} "$INSTDIR\chengyin-install.txt"
    ReadRegStr $0 HKLM "${CLASS}\InprocServer32" ""
    ReadRegStr $1 HKLM "${ARP}" "InstallLocation"
    ${If} $0 == ""
    ${AndIf} $1 != $INSTDIR
      ; Repeated cleanup may remove only the leftover uninstaller/directory.
      ; Other files are retained when the ownership marker is absent.
      Delete /REBOOTOK "$INSTDIR\Uninstall.exe"
      RMDir /REBOOTOK "$INSTDIR"
      SetErrorLevel 0
      Goto un_done
    ${EndIf}
  ${EndIf}
  ClearErrors
  FileOpen $0 "$INSTDIR\chengyin-install.txt" r
  FileRead $0 $1
  FileClose $0
  ${TrimNewLines} "$1" $1
  ${If} ${Errors}
  ${OrIf} $1 != "${VERSION}"
    StrCpy $Failure "安装标记缺失或不匹配，已保留文件。"
    Goto un_failed
  ${EndIf}
  ${If} ${FileExists} "$INSTDIR\chengyin_probe.exe"
    ExecWait '$\"$INSTDIR\chengyin_probe.exe$\" --check-registry' $0
    ${If} ${Errors}
    ${OrIf} $0 != 0
      StrCpy $Failure "无法安全读取已有注册，已保留文件。"
      Goto un_failed
    ${EndIf}
  ${EndIf}
  ReadRegStr $0 HKLM "${CLASS}\InprocServer32" ""
  ${If} $0 != ""
    ${If} $0 != "$INSTDIR\chengyin_tsf.dll"
      StrCpy $Failure "当前注册属于其他目录，已保留全部文件。"
      Goto un_failed
    ${EndIf}
  ${EndIf}
  ${If} ${FileExists} "$INSTDIR\chengyin_tsf.dll"
    ; The DLL also checks registration ownership/access, including when a
    ; registry read reports no server. Never delete a DLL after failed cleanup.
    ClearErrors
    ExecWait '$\"$SYSDIR\regsvr32.exe$\" /s /u $\"$INSTDIR\chengyin_tsf.dll$\"' $0
    ${If} ${Errors}
    ${OrIf} $0 != 0
      StrCpy $Failure "输入服务注销未完成，已保留文件，可稍后重试。"
      Goto un_failed
    ${EndIf}
  ${ElseIf} $0 != ""
    StrCpy $Failure "已注册的输入服务文件缺失，已保留其他文件。"
    Goto un_failed
  ${EndIf}
  ReadRegStr $0 HKLM "${ARP}" "InstallLocation"
  ${If} $0 == $INSTDIR
    ClearErrors
    DeleteRegKey HKLM "${ARP}"
    ${If} ${Errors}
      StrCpy $Failure "无法删除卸载记录，已保留安装文件，可重试。"
      Goto un_failed
    ${EndIf}
    !insertmacro RemoveLinks "澄音输入法"
  ${EndIf}
  SetOutPath "$TEMP"
  !insertmacro RemoveKnown "$INSTDIR"
  RMDir "$PROGRAMFILES64\ChengyinIME"
  DetailPrint "注销完成。应用占用的文件将在重新启动后删除；用户添加的文件予以保留。"
  SetErrorLevel 0
  Goto un_done
un_failed:
  DetailPrint "$Failure"
  MessageBox MB_OK|MB_ICONSTOP "$Failure" /SD IDOK
  SetErrorLevel 1
  Abort
un_done:
SectionEnd
