// GENERATED by scripts/version.py from version.json. Do not edit by hand.
#pragma once
#define CHENGYIN_VERSION L"0.1.0-preview33"
#define CHENGYIN_VERSION_NUMERIC L"0.1.0.33"
#define CHENGYIN_REVISION 33
// The next release an update check may legitimately offer. Update fixtures derive
// from this, so bumping the version cannot leave them testing a stale tag (R13).
#define CHENGYIN_FUTURE_VERSION L"0.1.0-preview34"
// Narrow forms used to build fixture text (JSON release responses, file names).
#define CHENGYIN_CURRENT_TAG_UTF8 "0.1.0-preview33"
#define CHENGYIN_FUTURE_TAG_UTF8 "0.1.0-preview34"
