// GENERATED by scripts/version.py from version.json. Do not edit by hand.
#pragma once
#define MYSWY_VERSION L"0.1.0-preview24"
#define MYSWY_VERSION_NUMERIC L"0.1.0.24"
#define MYSWY_REVISION 24
// The next release an update check may legitimately offer. Update fixtures derive
// from this, so bumping the version cannot leave them testing a stale tag (R13).
#define MYSWY_FUTURE_VERSION L"0.1.0-preview25"
// Narrow forms used to build fixture text (JSON release responses, file names).
#define MYSWY_CURRENT_TAG_UTF8 "0.1.0-preview24"
#define MYSWY_FUTURE_TAG_UTF8 "0.1.0-preview25"
