// SPDX-License-Identifier: GPL-3.0-or-later
//! Independent quality baseline over the annotated corpus (review R11).
//!
//! Measures only the shared Rust core: no UI, no disk, no platform adapter. The
//! corpus is `data/eval/quality.tsv`, generated by `scripts/generate_eval_corpus.py`
//! from the pinned dictionary; see `docs/QUALITY_BASELINE.md` for provenance,
//! licensing and metric definitions.
//!
//! Run:
//!     cargo run --release -p chengyin-core --example quality_report --locked
//!
//! Every row is replayed key by key through one fresh [`Session`] so rows cannot
//! influence each other. A `train` cell holds `;`-separated steps, applied in the
//! order written, which is what lets a row say *when* something was learned:
//!
//! * `record:<spelling>=><text>` — one host-confirmed selection written straight
//!   into the profile. Unattested text is never offered on the candidate page, so
//!   this is the only way to train it; it is the same call the platform adapter
//!   makes when it loads a saved profile.
//! * `ctx:<spelling>=><text>` — one host-confirmed selection *replayed on the
//!   session*: type the spelling, pick the text on the candidate page, acknowledge
//!   the write. It trains through `Profile::record_selection` (so the same key's
//!   competing readings are also observed as skipped) and, because the commit is
//!   real, it leaves `text` as the session's preceding-word context for whatever
//!   step or measured input follows.
//! * `idle:<n>` — `n` selections of one unrelated key. They observe nothing about
//!   the row's key and exist only to advance the profile's event clock, which is
//!   the clock `Preference::recent` decays against (one epoch per 256 events).

use chengyin_core::{Dictionary, Key, Modifiers, Profile, Session};
use std::collections::BTreeMap;
use std::sync::Arc;

/// First-page size the report treats as "Top-N" (the engine's visible page).
const TOP_N: usize = 9;
const MAX_PAGES: usize = 200;

struct Row {
    category: String,
    split: String,
    flags: u32,
    input: String,
    expected: String,
    train: Vec<TrainStep>,
    bucket: String,
}

/// One state-setting step applied before the row is measured.
enum TrainStep {
    /// `record:key=>text`: written straight into the profile. An unattested
    /// selection is never on the candidate page, so it cannot be selected there.
    Record { spelling: String, text: String },
    /// `ctx:key=>text`: replayed on the session so its committed word becomes the
    /// preceding-word context. See the module docs.
    Context { spelling: String, text: String },
    /// `idle:n`: `n` selections of one unrelated key, to advance the event clock.
    Idle(u32),
}

/// The throwaway key the `idle:` step records against. It exists only to make the
/// profile's event counter advance; no row in the corpus is measured on it, so its
/// own entry never competes with a measured key.
const IDLE_KEY: &str = "chengyinidlekey";
const IDLE_TEXT: &str = "闲";

/// Split one `train` cell entry into its step. The cell is generated, so an
/// unrecognized form is a generator bug and fails loudly rather than being
/// silently skipped as an empty step.
fn parse_step(step: &str) -> TrainStep {
    if let Some(rest) = step.strip_prefix("idle:") {
        return TrainStep::Idle(rest.parse().expect("idle count"));
    }
    let (head, text) = step
        .split_once("=>")
        .unwrap_or_else(|| panic!("train step {step:?}"));
    let (context, spelling) = match head.strip_prefix("ctx:") {
        Some(rest) => (true, rest),
        None => (
            false,
            head.strip_prefix("record:").expect("train step prefix"),
        ),
    };
    let (spelling, text) = (spelling.to_owned(), text.to_owned());
    if context {
        TrainStep::Context { spelling, text }
    } else {
        TrainStep::Record { spelling, text }
    }
}

fn load(source: &str) -> Vec<Row> {
    let mut rows = Vec::new();
    for (index, line) in source.lines().enumerate() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(
            fields.len(),
            8,
            "line {}: {} fields",
            index + 1,
            fields.len()
        );
        let train = if fields[5].is_empty() {
            Vec::new()
        } else {
            fields[5].split(';').map(parse_step).collect()
        };
        rows.push(Row {
            category: fields[0].to_owned(),
            split: fields[1].to_owned(),
            flags: fields[2].parse().expect("flags"),
            input: fields[3].to_owned(),
            expected: fields[4].to_owned(),
            train,
            bucket: fields[6].to_owned(),
        });
    }
    rows
}

fn type_keys(session: &mut Session, text: &str) {
    for character in text.chars() {
        session.process(Key::Character(character), Modifiers::default());
    }
}

fn visible_texts(session: &Session) -> Vec<String> {
    (0..session.candidate_count())
        .map(|i| session.candidate(i).unwrap().text.to_owned())
        .collect()
}

/// Index of `text` in the paged candidate list, plus how many pages were turned.
fn find_paged(session: &mut Session, text: &str) -> Option<(usize, usize)> {
    let mut pages = 0;
    loop {
        let at =
            (0..session.candidate_count()).find(|&i| session.candidate(i).unwrap().text == text);
        if let Some(at) = at {
            let page_index = session.page();
            return Some((at, page_index));
        }
        if !session.has_next_page() || pages >= MAX_PAGES {
            return None;
        }
        session.process(Key::PageDown, Modifiers::default());
        pages += 1;
    }
}

/// Build the profile the row measures. `record:` steps are applied straight to it
/// — the same entry point the platform adapter uses when it loads a saved profile,
/// and the only way to train unattested text, which the candidate page never
/// offers. `idle:` steps run on the profile too, since they only advance its event
/// clock. `ctx:` steps are left to [`apply_context_steps`], which needs the live
/// session, and are applied in the order written among themselves.
fn build_profile(row: &Row) -> Profile {
    let mut profile = Profile::default();
    for step in &row.train {
        match step {
            TrainStep::Record { spelling, text } => assert!(
                profile.record(spelling, text),
                "rejected train step {spelling} => {text}"
            ),
            TrainStep::Idle(count) => {
                for _ in 0..*count {
                    assert!(profile.record(IDLE_KEY, IDLE_TEXT));
                }
            }
            TrainStep::Context { .. } => {}
        }
    }
    profile
}

/// Replay the row's `ctx:` steps on the session, in written order. Each one types
/// its spelling, selects the named text from the candidate page, and acknowledges
/// the host write — the same three calls a platform adapter makes. Because the
/// commit is real, the text also becomes the session's preceding-word context for
/// the next step and for the row's own measured input.
fn apply_context_steps(session: &mut Session, row: &Row) {
    for step in &row.train {
        let TrainStep::Context { spelling, text } = step else {
            continue;
        };
        session.reset();
        type_keys(session, spelling);
        let (at, _) = find_paged(session, text)
            .unwrap_or_else(|| panic!("ctx step {spelling} => {text}: not on any page"));
        assert!(
            session
                .process(Key::Select(at), Modifiers::default())
                .handled
        );
        assert_eq!(session.commit(), text, "ctx step {spelling} => {text}");
        assert!(
            session.learn_commit(),
            "ctx step {spelling} => {text}: write not acknowledged"
        );
    }
}

/// One row's outcome.
#[derive(Default, Clone, Copy)]
struct Score {
    top1: bool,
    top_n: bool,
    full: bool,
    /// Top-1 is a synthesized combination rather than a lexicon entry.
    combination: bool,
    /// Top-1 is a synthesized combination *and* is not the expected text.
    wrong_combination: bool,
    /// Keystrokes to select the expected text (typing + page turns + selection).
    keys: Option<u32>,
}

fn score(dictionary: &Arc<Dictionary>, row: &Row, incremental: bool) -> Score {
    let mut session = Session::new(Arc::clone(dictionary));
    session.configure(TOP_N, true, false);
    session.configure_matching(row.flags);
    session.configure_incremental(incremental);
    let profile = build_profile(row);
    assert!(session.set_profile(Arc::new(profile)));
    session.reset();
    // Context steps run on this same session and the last one leaves it with an
    // empty composition and the committed word as its context — which is exactly
    // the state the measured input must start from. `Session::reset` would clear
    // that context, so it is deliberately not called again here.
    apply_context_steps(&mut session, row);
    type_keys(&mut session, &row.input);

    let mut result = Score::default();
    let first = session
        .candidate(0)
        .map(|c| (c.text.to_owned(), c.frequency));
    if let Some((text, frequency)) = &first {
        result.top1 = text == &row.expected;
        result.combination = *frequency == 0;
        result.wrong_combination = result.combination && !result.top1;
    }
    let page = visible_texts(&session);
    result.top_n = page.iter().any(|text| text == &row.expected);
    if let Some((_at, pages)) = find_paged(&mut session, &row.expected) {
        result.full = true;
        // Typed characters, one key per turned page, one key to select.
        result.keys = Some(row.input.chars().count() as u32 + pages as u32 + 1);
    }
    result
}

fn percentile(samples: &mut [u32], p: usize) -> u32 {
    if samples.is_empty() {
        return 0;
    }
    samples.sort_unstable();
    samples[(samples.len() * p / 100).min(samples.len() - 1)]
}

struct Aggregate {
    rows: u32,
    top1: u32,
    top_n: u32,
    full: u32,
    combination: u32,
    wrong_combination: u32,
    keys: Vec<u32>,
}

impl Aggregate {
    fn new() -> Self {
        Self {
            rows: 0,
            top1: 0,
            top_n: 0,
            full: 0,
            combination: 0,
            wrong_combination: 0,
            keys: Vec::new(),
        }
    }
    fn push(&mut self, score: Score) {
        self.rows += 1;
        self.top1 += u32::from(score.top1);
        self.top_n += u32::from(score.top_n);
        self.full += u32::from(score.full);
        self.combination += u32::from(score.combination);
        self.wrong_combination += u32::from(score.wrong_combination);
        if let Some(keys) = score.keys {
            self.keys.push(keys);
        }
    }
    fn line(&self, label: &str) -> String {
        let share = |value: u32| 100.0 * f64::from(value) / f64::from(self.rows.max(1));
        let mut keys = self.keys.clone();
        let median = percentile(&mut keys, 50);
        let p95 = percentile(&mut keys, 95);
        format!(
            "{label:<26} n={:<4} top1={:>5.1}%  top{TOP_N}={:>5.1}%  full={:>5.1}%  combo={:>5.1}%  wrongCombo={:>5.1}%  keysP50={} keysP95={}",
            self.rows,
            share(self.top1),
            share(self.top_n),
            share(self.full),
            share(self.combination),
            share(self.wrong_combination),
            median,
            p95,
        )
    }
}

fn main() {
    let args: Vec<_> = std::env::args().skip(1).collect();
    let incremental = args.iter().any(|arg| arg == "--incremental");
    let mut paths = args.iter().filter(|arg| arg.as_str() != "--incremental");
    let path = paths.next().map_or("data/eval/quality.tsv", String::as_str);
    assert!(
        paths.next().is_none(),
        "usage: quality_report [corpus.tsv] [--incremental]"
    );
    let source = std::fs::read_to_string(path).expect("read the corpus");
    let rows = load(&source);
    assert!(!rows.is_empty(), "empty corpus");

    let bytes = include_bytes!("../../../data/daily.mswydict");
    let start = std::time::Instant::now();
    let dictionary = Arc::new(Dictionary::from_binary(bytes).unwrap());
    println!(
        "corpus={path} incremental={incremental} rows={} dictionary entries={} load={}us",
        rows.len(),
        dictionary.entry_count(),
        start.elapsed().as_micros()
    );
    println!(
        "metric definitions: top1=first candidate; top{TOP_N}=first page; full=any page (<= {MAX_PAGES}); \
         combo=first candidate is a synthesized combination (frequency 0); \
         wrongCombo=combo and not the expected text; keys=typed keys + page turns + selection"
    );

    let mut by_category: BTreeMap<&str, Aggregate> = BTreeMap::new();
    let mut by_split: BTreeMap<&str, Aggregate> = BTreeMap::new();
    let mut by_bucket: BTreeMap<&str, Aggregate> = BTreeMap::new();
    let mut overall = Aggregate::new();
    for row in &rows {
        let score = score(&dictionary, row, incremental);
        by_category
            .entry(row.category.as_str())
            .or_insert_with(Aggregate::new)
            .push(score);
        by_split
            .entry(row.split.as_str())
            .or_insert_with(Aggregate::new)
            .push(score);
        by_bucket
            .entry(row.bucket.as_str())
            .or_insert_with(Aggregate::new)
            .push(score);
        overall.push(score);
    }

    println!("\n== by category ==");
    for (category, aggregate) in &by_category {
        println!("{}", aggregate.line(category));
    }
    println!("\n== by split ==");
    for (split, aggregate) in &by_split {
        println!("{}", aggregate.line(split));
    }
    println!("\n== by difficulty bucket ==");
    for (bucket, aggregate) in &by_bucket {
        println!("{}", aggregate.line(bucket));
    }
    println!("\n== overall ==");
    println!("{}", overall.line("all"));
}
