//! Independent quality baseline over the annotated corpus (review R11).
//!
//! Measures only the shared Rust core: no UI, no disk, no platform adapter. The
//! corpus is `data/eval/quality.tsv`, generated by `scripts/generate_eval_corpus.py`
//! from the pinned dictionary; see `docs/QUALITY_BASELINE.md` for provenance,
//! licensing and metric definitions.
//!
//! Run:
//!     cargo run --release -p myswy-core --example quality_report --locked
//!
//! Every row is replayed key by key through one fresh [`Session`] so rows cannot
//! influence each other. Rows with a `train` column first replay the recorded
//! host-confirmed selections, which is what builds the learning profile.

use myswy_core::{Dictionary, Key, Modifiers, Profile, Session};
use std::collections::BTreeMap;
use std::sync::Arc;

/// First-page size the report treats as "Top-N" (the engine's visible page).
const TOP_N: usize = 9;
const MAX_PAGES: usize = 200;

struct Row {
    category: String,
    split: String,
    flags: u32,
    input: String,
    expected: String,
    train: Vec<TrainStep>,
    bucket: String,
}

/// One host-confirmed selection to apply before the row is measured.
struct TrainStep {
    /// `record:key=>text`: written straight into the profile. An unattested
    /// selection is never on the candidate page, so it cannot be selected there.
    record: bool,
    spelling: String,
    text: String,
}

fn load(source: &str) -> Vec<Row> {
    let mut rows = Vec::new();
    for (index, line) in source.lines().enumerate() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(
            fields.len(),
            8,
            "line {}: {} fields",
            index + 1,
            fields.len()
        );
        let train = if fields[5].is_empty() {
            Vec::new()
        } else {
            fields[5]
                .split(';')
                .map(|step| {
                    let (head, text) = step.split_once("=>").expect("train step");
                    let (record, spelling) = match head.strip_prefix("record:") {
                        Some(rest) => (true, rest),
                        None => (false, head),
                    };
                    TrainStep {
                        record,
                        spelling: spelling.to_owned(),
                        text: text.to_owned(),
                    }
                })
                .collect()
        };
        rows.push(Row {
            category: fields[0].to_owned(),
            split: fields[1].to_owned(),
            flags: fields[2].parse().expect("flags"),
            input: fields[3].to_owned(),
            expected: fields[4].to_owned(),
            train,
            bucket: fields[6].to_owned(),
        });
    }
    rows
}

fn type_keys(session: &mut Session, text: &str) {
    for character in text.chars() {
        session.process(Key::Character(character), Modifiers::default());
    }
}

fn visible_texts(session: &Session) -> Vec<String> {
    (0..session.candidate_count())
        .map(|i| session.candidate(i).unwrap().text.to_owned())
        .collect()
}

/// Index of `text` in the paged candidate list, plus how many pages were turned.
fn find_paged(session: &mut Session, text: &str) -> Option<(usize, usize)> {
    let mut pages = 0;
    loop {
        let at =
            (0..session.candidate_count()).find(|&i| session.candidate(i).unwrap().text == text);
        if let Some(at) = at {
            let page_index = session.page();
            return Some((at, page_index));
        }
        if !session.has_next_page() || pages >= MAX_PAGES {
            return None;
        }
        session.process(Key::PageDown, Modifiers::default());
        pages += 1;
    }
}

/// Build the profile the row measures. Every `train` step is a selection the host
/// already confirmed, so it is applied straight to the profile — the same entry
/// point the platform adapter uses when it loads a saved profile. Unattested text
/// is never offered on the candidate page, so it could not be selected there.
fn build_profile(row: &Row) -> Profile {
    let mut profile = Profile::default();
    for step in &row.train {
        assert!(step.record, "only record: steps are supported");
        assert!(
            profile.record(&step.spelling, &step.text),
            "rejected train step {} => {}",
            step.spelling,
            step.text
        );
    }
    profile
}

/// One row's outcome.
#[derive(Default, Clone, Copy)]
struct Score {
    top1: bool,
    top_n: bool,
    full: bool,
    /// Top-1 is a synthesized combination rather than a lexicon entry.
    combination: bool,
    /// Top-1 is a synthesized combination *and* is not the expected text.
    wrong_combination: bool,
    /// Keystrokes to select the expected text (typing + page turns + selection).
    keys: Option<u32>,
}

fn score(dictionary: &Arc<Dictionary>, row: &Row, incremental: bool) -> Score {
    let mut session = Session::new(Arc::clone(dictionary));
    session.configure(TOP_N, true, false);
    session.configure_matching(row.flags);
    session.configure_incremental(incremental);
    let profile = build_profile(row);
    assert!(session.set_profile(Arc::new(profile)));
    session.reset();
    type_keys(&mut session, &row.input);

    let mut result = Score::default();
    let first = session
        .candidate(0)
        .map(|c| (c.text.to_owned(), c.frequency));
    if let Some((text, frequency)) = &first {
        result.top1 = text == &row.expected;
        result.combination = *frequency == 0;
        result.wrong_combination = result.combination && !result.top1;
    }
    let page = visible_texts(&session);
    result.top_n = page.iter().any(|text| text == &row.expected);
    if let Some((_at, pages)) = find_paged(&mut session, &row.expected) {
        result.full = true;
        // Typed characters, one key per turned page, one key to select.
        result.keys = Some(row.input.chars().count() as u32 + pages as u32 + 1);
    }
    result
}

fn percentile(samples: &mut [u32], p: usize) -> u32 {
    if samples.is_empty() {
        return 0;
    }
    samples.sort_unstable();
    samples[(samples.len() * p / 100).min(samples.len() - 1)]
}

struct Aggregate {
    rows: u32,
    top1: u32,
    top_n: u32,
    full: u32,
    combination: u32,
    wrong_combination: u32,
    keys: Vec<u32>,
}

impl Aggregate {
    fn new() -> Self {
        Self {
            rows: 0,
            top1: 0,
            top_n: 0,
            full: 0,
            combination: 0,
            wrong_combination: 0,
            keys: Vec::new(),
        }
    }
    fn push(&mut self, score: Score) {
        self.rows += 1;
        self.top1 += u32::from(score.top1);
        self.top_n += u32::from(score.top_n);
        self.full += u32::from(score.full);
        self.combination += u32::from(score.combination);
        self.wrong_combination += u32::from(score.wrong_combination);
        if let Some(keys) = score.keys {
            self.keys.push(keys);
        }
    }
    fn line(&self, label: &str) -> String {
        let share = |value: u32| 100.0 * f64::from(value) / f64::from(self.rows.max(1));
        let mut keys = self.keys.clone();
        let median = percentile(&mut keys, 50);
        let p95 = percentile(&mut keys, 95);
        format!(
            "{label:<26} n={:<4} top1={:>5.1}%  top{TOP_N}={:>5.1}%  full={:>5.1}%  combo={:>5.1}%  wrongCombo={:>5.1}%  keysP50={} keysP95={}",
            self.rows,
            share(self.top1),
            share(self.top_n),
            share(self.full),
            share(self.combination),
            share(self.wrong_combination),
            median,
            p95,
        )
    }
}

fn main() {
    let args: Vec<_> = std::env::args().skip(1).collect();
    let incremental = args.iter().any(|arg| arg == "--incremental");
    let mut paths = args.iter().filter(|arg| arg.as_str() != "--incremental");
    let path = paths.next().map_or("data/eval/quality.tsv", String::as_str);
    assert!(
        paths.next().is_none(),
        "usage: quality_report [corpus.tsv] [--incremental]"
    );
    let source = std::fs::read_to_string(path).expect("read the corpus");
    let rows = load(&source);
    assert!(!rows.is_empty(), "empty corpus");

    let bytes = include_bytes!("../../../data/daily.mswydict");
    let start = std::time::Instant::now();
    let dictionary = Arc::new(Dictionary::from_binary(bytes).unwrap());
    println!(
        "corpus={path} incremental={incremental} rows={} dictionary entries={} load={}us",
        rows.len(),
        dictionary.entry_count(),
        start.elapsed().as_micros()
    );
    println!(
        "metric definitions: top1=first candidate; top{TOP_N}=first page; full=any page (<= {MAX_PAGES}); \
         combo=first candidate is a synthesized combination (frequency 0); \
         wrongCombo=combo and not the expected text; keys=typed keys + page turns + selection"
    );

    let mut by_category: BTreeMap<&str, Aggregate> = BTreeMap::new();
    let mut by_split: BTreeMap<&str, Aggregate> = BTreeMap::new();
    let mut by_bucket: BTreeMap<&str, Aggregate> = BTreeMap::new();
    let mut overall = Aggregate::new();
    for row in &rows {
        let score = score(&dictionary, row, incremental);
        by_category
            .entry(row.category.as_str())
            .or_insert_with(Aggregate::new)
            .push(score);
        by_split
            .entry(row.split.as_str())
            .or_insert_with(Aggregate::new)
            .push(score);
        by_bucket
            .entry(row.bucket.as_str())
            .or_insert_with(Aggregate::new)
            .push(score);
        overall.push(score);
    }

    println!("\n== by category ==");
    for (category, aggregate) in &by_category {
        println!("{}", aggregate.line(category));
    }
    println!("\n== by split ==");
    for (split, aggregate) in &by_split {
        println!("{}", aggregate.line(split));
    }
    println!("\n== by difficulty bucket ==");
    for (bucket, aggregate) in &by_bucket {
        println!("{}", aggregate.line(bucket));
    }
    println!("\n== overall ==");
    println!("{}", overall.line("all"));
}
