#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Single, audited release-version source (review R13).

`version.json` at the repository root is the only place a release version is
written by hand. The Windows UI strings, the updater's current version and user
agent, the installer metadata and the CI package path are all generated or
checked from here, so those surfaces cannot silently drift apart.

Usage:
    python3 scripts/version.py --print tag
    python3 scripts/version.py --print package-name --toolchain msvc
    python3 scripts/version.py --generate
    python3 scripts/version.py --check
    python3 scripts/version.py --verify-bump
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "version.json"
GENERATED_HEADER = ROOT / "platforms/windows/version_generated.h"
GENERATED_MARKER = "GENERATED by scripts/version.py"


class Version:
    def __init__(self, version: str, preview: int) -> None:
        self.version = version
        self.preview = preview

    @property
    def tag(self) -> str:
        return f"{self.version}-preview{self.preview}"

    @property
    def arch_pkgver(self) -> str:
        # Arch's pkgver may not contain the hyphen used as the pkgver/pkgrel
        # separator, so the same release text is written with dots. vercmp orders
        # 0.1.0.preview26 < 0.1.0.preview27 monotonically, which is what pacman
        # needs for upgrades.
        return f"{self.version}.preview{self.preview}"

    @property
    def numeric(self) -> str:
        # Four-field Windows product version: base version plus the preview number.
        return f"{self.version}.{self.preview}"

    @property
    def future_tag(self) -> str:
        # The next release an update check could legitimately be offered. Update
        # fixtures derive from this instead of a written literal (review R13).
        return f"{self.version}-preview{self.preview + 1}"

    def package_name(self, toolchain: str) -> str:
        return f"chengyin-windows-x64-{self.tag}-{toolchain}.exe"


def load() -> Version:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    version = data["version"]
    preview = data["preview"]
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise ValueError(f"version.json: bad base version {version!r}")
    if not isinstance(preview, int) or not 1 <= preview <= 998:
        # The derived future tag must stay inside the packager's 1..999 bound.
        raise ValueError(f"version.json: preview must be 1..998, got {preview!r}")
    return Version(version, preview)


def render_header(current: Version) -> str:
    # Plain macros, not constexpr arrays: a release string must stay usable in
    # wide literal concatenation (L"版本：" CHENGYIN_VERSION), which an array is not.
    return f"""// {GENERATED_MARKER} from version.json. Do not edit by hand.
#pragma once
#define CHENGYIN_VERSION L"{current.tag}"
#define CHENGYIN_VERSION_NUMERIC L"{current.numeric}"
#define CHENGYIN_REVISION {current.preview}
// The next release an update check may legitimately offer. Update fixtures derive
// from this, so bumping the version cannot leave them testing a stale tag (R13).
#define CHENGYIN_FUTURE_VERSION L"{current.future_tag}"
// Narrow forms used to build fixture text (JSON release responses, file names).
#define CHENGYIN_CURRENT_TAG_UTF8 "{current.tag}"
#define CHENGYIN_FUTURE_TAG_UTF8 "{current.future_tag}"
"""


def write_header() -> None:
    GENERATED_HEADER.write_text(render_header(load()), encoding="utf-8", newline="\n")


def verify_bump(current: Version) -> int:
    """Prove a synthetic bump reaches every derived surface (review R13).

    The header is regenerated as if `preview` had been incremented, and each value
    the build, UI and updater read must move with the source. The working tree is
    left untouched: the generated header is restored before returning.
    """
    bumped = Version(current.version, current.preview + 1)
    original = GENERATED_HEADER.read_text(encoding="utf-8") if GENERATED_HEADER.is_file() else ""
    try:
        GENERATED_HEADER.write_text(render_header(bumped), encoding="utf-8", newline="\n")
        rendered = GENERATED_HEADER.read_text(encoding="utf-8")
    finally:
        if original:
            GENERATED_HEADER.write_text(original, encoding="utf-8", newline="\n")
    checks = {
        "tag": f'#define CHENGYIN_VERSION L"{bumped.tag}"' in rendered,
        "numeric": f'#define CHENGYIN_VERSION_NUMERIC L"{bumped.numeric}"' in rendered,
        "revision": f"#define CHENGYIN_REVISION {bumped.preview}" in rendered,
        "future-tag": f'#define CHENGYIN_FUTURE_TAG_UTF8 "{bumped.future_tag}"' in rendered,
        "changed": bumped.tag != current.tag,
    }
    failed = [name for name, ok in checks.items() if not ok]
    if failed:
        print(f"bump not propagated: {', '.join(failed)}", file=sys.stderr)
        return 1
    if GENERATED_HEADER.read_text(encoding="utf-8") != original:
        print("bump verification did not restore the generated header", file=sys.stderr)
        return 1
    print(f"OK: a bump to {bumped.tag} regenerates tag/numeric/revision/future tag "
          f"and the package name {bumped.package_name('msvc')}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print", dest="show",
                        choices=("tag", "version", "preview", "numeric", "future-tag", "package-name",
                                 "arch-pkgver"))
    parser.add_argument("--toolchain", default="msvc", choices=("msvc", "gnu"))
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verify-bump", action="store_true",
                        help="prove a synthetic bump regenerates every derived surface")
    args = parser.parse_args()
    current = load()
    if args.verify_bump:
        return verify_bump(current)
    if args.generate:
        write_header()
        print(f"Wrote {GENERATED_HEADER.relative_to(ROOT)} for {current.tag}")
        return 0
    if args.check:
        expected = render_header(current)
        actual = GENERATED_HEADER.read_text(encoding="utf-8") if GENERATED_HEADER.is_file() else ""
        if actual != expected:
            print(f"stale: {GENERATED_HEADER.relative_to(ROOT)} does not match version.json",
                  file=sys.stderr)
            return 1
        workspace = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
        cargo_version = workspace["workspace"]["package"]["version"]
        if cargo_version != current.version:
            print(f"drift: Cargo.toml is {cargo_version} but version.json is {current.version}",
                  file=sys.stderr)
            return 1
        # The Arch package restates the version as a literal pkgver, because pacman
        # cannot read version.json. Keep that one copy honest here so a stale pkgver
        # cannot ship a mislabelled package.
        arch = ROOT / "packaging/arch/PKGBUILD"
        if arch.is_file():
            match = re.search(r"^pkgver=(\S+)$", arch.read_text(encoding="utf-8"), re.M)
            if not match or match.group(1) != current.arch_pkgver:
                print(f"drift: packaging/arch/PKGBUILD pkgver is "
                      f"{match.group(1) if match else 'missing'} but version.json implies "
                      f"{current.arch_pkgver}", file=sys.stderr)
                return 1
        print(f"OK: {current.tag} (Cargo {cargo_version}, header and Arch pkgver in sync)")
        return 0
    if args.show == "package-name":
        print(current.package_name(args.toolchain))
    elif args.show:
        print({
            "tag": current.tag, "version": current.version, "preview": current.preview,
            "numeric": current.numeric, "future-tag": current.future_tag,
            "arch-pkgver": current.arch_pkgver,
        }[args.show])
    else:
        parser.error("pass --generate, --check, --verify-bump or --print")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
